In [6]:
#Packages to data analysis
import numpy as np
import pandas as pd
import seaborn as sn
import csv
import sys
import xgboost as xgb #first I install with pip install xgboost)
from IPython.display import display

#Packages to graph
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler

#Packages to the model 
from sklearn.model_selection import train_test_split

# Data

In [7]:
#Import Data as csv but it could be txt also 

table=pd.read_csv('Soccer.csv')
table

,Sea,Lge,Date,HT,AT,HS,AS,GD,WDL
0,00-01,ARG1,30/07/2000,Boca Juniors,Argentinos Juniors,4,0,4,W
1,00-01,ARG1,30/07/2000,Chacarita Juniors,Union de Santa Fe,0,0,0,D
2,00-01,ARG1,30/07/2000,CA Colon,Huracan,1,1,0,D
3,00-01,ARG1,30/07/2000,Estudiantes,River Plate,1,1,0,D
4,00-01,ARG1,30/07/2000,Independiente,Belgrano Cordoba,0,0,0,D
...,...,...,...,...,...,...,...,...,...
251387,18-19,ZAF1,11/05/2019,Chippa United,Kaizer Chiefs,1,0,1,W
251388,18-19,ZAF1,11/05/2019,Free State Stars,Mamelodi Sundowns,0,1,-1,L
251389,18-19,ZAF1,11/05/2019,Golden Arrows,BidVest Wits,0,1,-1,L
251390,18-19,ZAF1,11/05/2019,Orlando Pirates,Polokwane City,3,0,3,W
251391,18-19,ZAF1,11/05/2019,SuperSport United,Highlands Park,0,2,-2,L

#                     DATA PREPARATION

### Exploring the data

In [8]:
#Exploring the data, looking for inconsistences, etc. #Only with cvs 

with open ('Soccer.csv') as csvfile:
    mpg=list(csv.DictReader(csvfile))
#mpg[:3]

Leagues = set(d['Lge'] for d in mpg)
#print(Leagues)
# The inconsistence is'mar-01'

Season= set(d['Sea'] for d in mpg)
#print(Season)
#The inconsistences are '01-feb','02-mar','03-abr','04-may','05-jun','06-jul','07-ago','08-sep','09-oct','10-nov','11-dic','dic-13' 

Home= set(d['HT'] for d in mpg)
#print(Home)

In [9]:
#reorder the date 
table['Date'] = table['Date'].map(pd.to_datetime)
table['Date'].tail()

251387   2019-11-05
251388   2019-11-05
251389   2019-11-05
251390   2019-11-05
251391   2019-11-05
Name: Date, dtype: datetime64[ns]

In [10]:
#Get the year from date and add a new column
def get_year(dt):
    return dt.year

table['Year'] = table['Date'].map(get_year)

table.head()

,Sea,Lge,Date,HT,AT,HS,AS,GD,WDL,Year
0,00-01,ARG1,2000-07-30,Boca Juniors,Argentinos Juniors,4,0,4,W,2000
1,00-01,ARG1,2000-07-30,Chacarita Juniors,Union de Santa Fe,0,0,0,D,2000
2,00-01,ARG1,2000-07-30,CA Colon,Huracan,1,1,0,D,2000
3,00-01,ARG1,2000-07-30,Estudiantes,River Plate,1,1,0,D,2000
4,00-01,ARG1,2000-07-30,Independiente,Belgrano Cordoba,0,0,0,D,2000

### Filtering the data

#####  NOR1

In [11]:
#Because of the inconsistences in Season and Lge
#RelevantYear=['2017','2018','2019']
RelevantLeague=['NOR1']
#Trial_P3=['']
#table4=table['Lge']=table['Lge'].replace({'mar-01':'MOR1'}) 
#table1 = table[table['Lge'] != 'mar-01'] #League
table1=table[table['Lge'].isin(RelevantLeague)] #By team chosen
#table2=table1[table1['Year'].isin(RelevantYear)] #Last 3 years

In [15]:
table1.head()
table1['Year'].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019], dtype=int64)

### Transforming the data to a numerical value

##### Dictionaries

In [58]:
#Dictionary for the teams

listHome= ('Fulham', 'Darmstadt 98', 'Odd Grenland', 'Troyes', 'Fort Lauderdale Strikers', 'Maccabi Netanya', 'Sportfreunde Lotte', 'Athletic Bilbao', 'Zhejiang Yiteng', 'Newells Old Boys', 'Hamarkameratene', 'Jazz Pori', 'Consadole Sapporo', 'Espanyol Barcelona', 'Macae Esporte FC', 'Boavista', 'Ponferradina', 'Cowdenbeath', 'Kuopion PS', 'Pescara', 'Altay', 'Eintracht Trier', 'Belouizdad', 'Tigres de la Universidad Autonoma', 'Instituto Cordoba', 'Bourg Peronnas', 'Platanias', 'Triestina', 'HJK Helsinki', 'Rodez AF', 'CO Medenine', 'Santos FC', 'FC Seoul', 'Beijing Sanyaun', 'North Ferriby', 'Olympique Lyonnais', 'Real Salt Lake', 'Suwon City FC', 'Levadeiakos', 'FK Amkar Perm', 'River Ecuador', 'KagoshimaUtd', 'Deportes Melipilla', 'Southampton', 'Hapoel Raanana', 'Central Coast Mariners', 'GAIS Goteborg', 'Crystal Palace', 'Atromitos', 'Panserraikos', 'East Fife', 'Gwangju Sangmu', 'Jomo Cosmos', 'Hangzhou Greentown', 'ASM Belfort', 'Fortuna Dusseldorf', 'Cordoba', 'Tampere United', 'Schalke 04', 'Delemont', 'Hellas Verona', 'Dalian Haichang', 'Ceara SC', 'Heerenveen', 'FC Villefranche', 'AC Milan', 'Start Kristiansand', 'Esporte Clube Vitoria BA', 'Arles', 'Panathinaikos', 'Aberdeen', 'Lokomotiv Moscow', 'Marseille Consolat', 'Stranraer', 'Cesena', 'Real Betis', 'Chalkidona', 'Silver Stars', 'Shinnik Yaroslavl', 'Genoa', 'Shonan Bellmare', 'Kawkab AC Marrakech', 'Figueirense', 'Sarmiento de Junin', 'Salgueiros', 'De Graafschap', 'Barcelona', 'Bloemfontein Celtic', 'Allianssi', 'Santiago Morning', 'Hapoel Petach-Tikva', 'Olympiakos Volou', 'AlbinoLeffe', 'Tochigi SC', 'FK Khimki', 'BelAbbes', 'AFC Eskilstuna', 'Baltika Kaliningrad', 'North Queensland Fury', 'Avai FC', 'Lota Schwager', 'Salisbury', 'Edinburgh City', 'Aalborg', 'Black Leopards', 'Augsburg', 'Braunschweig', 'D.C. United', 'Guangzhou Evergrande', 'Holstein Kiel', 'Crawley Town', 'Meppen', 'Urena Sport Club', 'Kidderminster', 'Inverness CT', 'Millwall', 'Hibernian', 'Enisey Krasnoyarsk', 'Baroka FC', 'Cremonese', 'Giravanz', 'FC Lugano', 'WaiBOP United', 'New York Red Bulls', 'Canterbury United', 'Tianjin Quanjian', 'Chievo Verona', 'Carl Zeiss Jena', 'Vejle', 'Tupi FC', 'Moroka Swallows', 'New York Cosmos', 'FC Superfund', 'Guaratingueta', 'Bromley', 'Tuks FC', 'Grazer AK', 'SC Bastia', 'FK Tyumen', 'Free State Stars', 'Den Bosch', 'Falkenbergs', 'UD Las Palmas', 'CD Cobreloa', 'Hyeres FC', 'Aris', 'FC Karnten', 'Cambridge', 'Trabzonspor', 'NEC Nijmegen', 'Atlanta United FC', 'Carquefou JA', 'Bayern Munich II', 'Machida Zelvia', 'Leganes', 'Americana Futebol', 'Newport County', 'Schweinfurt', 'Grasshoppers Zurich', 'FK Tosno', 'Scarborough', 'Altrincham', 'Caracas FC', 'Maccabi Petach-Tikva', 'Universidad de Chile', 'Compostela', 'Preussen Munster', 'AC Ajaccio', 'RW Oberhausen', 'Roosendaal', 'Club Leon', 'Torpedo Moscow', 'Albion Rovers', 'America MG', 'Grombalia Sports', 'Trapani', 'Jyvaskyla', 'CD Cobresal', 'Lewes', 'Treviso', 'Aves', 'Cittadella', 'Colchester', 'Coritiba FC', 'Hearts', 'Crotone', 'Amiens SC', 'Club de Futbol America', 'Lazio', 'Blackburn Rovers', 'Marignane', 'GyE La Plata', 'Henan Jianye', 'Guimaraes', 'Cadiz', 'Setif', 'Carabobo FC', 'JS Kabylie', 'Nancy', 'Centro Italo', 'US Avranches', 'FC Volgar Astrakhan', 'Shenzhen FC', 'FK Torpedo Armavir', 'Genk', 'Esbjerg fB', 'AFC Wimbledon', 'EOG Kram', 'Groningen', 'Stirling Albion', 'CSD Rangers', 'FC Kobenhavn', 'Sydney United Pumas', 'FC St Gallen', 'SAS Epinal', 'Kavala', 'FC Cincinnati', 'FK Tom Tomsk', 'Corinthians Paulista', 'Arminia Bielefeld', 'Moreirense', 'Pontevedra', 'Kamatamare', 'Standard', 'Porto', 'Asteras Tripolis', 'Wydad de Fes', 'Nimes', 'Poli Ejido', 'Bristol Rovers', 'Santos Laguna', 'Deportivo Tachira', 'Raja Beni Mellal', 'Tokushima Vortis', 'SV Ried', 'Spartak Nalchik', 'Ljungskile SK', 'Sochi', 'Palermo', 'Orlando Pirates', 'Eskisehirspor', 'VfB Stuttgart', 'Falkirk', 'Changchun Yatai', 'Atletico El Vigia', 'Ancona 1905', 'CRB Ain Fakroun', 'Waikato FC', 'Hebei China Fortune FC', 'Stade de Reims', 'Willem II', 'Twente Enschede', 'Metallurg Lipetsk', 'Bucheon SK', 'Coventry City', 'Louvieroise', 'Ajax Cape Town', 'Gremio Barueri', 'Spartak Moscow', 'Parana Clube', 'Gretna', 'Nuneaton Town', 'Oud-Heverlee Leuven', 'Volendam', 'York City', 'Kallonis', 'Getafe', 'Atletico Mineiro', 'Halifax', 'Kashiwa Reysol', 'Alfreton Town', 'Waitakere United', 'Forfar Athletic', 'Hapoel Haifa', 'Perugia', 'Rotherham United', 'Ilves Tampere', 'Orebro SK', 'Kristiansund', 'CA San Martin', 'Guarani FC', 'Nagoya Grampus', 'Lleida', 'Dover Athletic', 'CD Palestino', 'Werder Bremen', 'Crucero del Norte', 'Santo Andre Esporte Clube', 'Lillestrom SK', 'Les Herbiers VF', 'Barnsley', 'Maritimo', 'Deportivo Quito', 'CD Olmedo', 'Akratitos', 'Pro Vercelli', 'AS Moulins', 'Club Sportif Sfaxien', 'Viborg', 'Heidenheim', 'Motherwell', 'Grosseto', 'Werder Bremen II', 'Tokyo Verdy', 'CD Clan Juvenil', 'Apollon', 'Assyriska', 'Constantine', 'August First Football Team', 'Huracan', 'Kalamata', 'Monagas', 'Hebei', 'Rizespor', 'San Martin Tucuman', 'Estudiantes de Merida', 'Delfin SC', 'Deportes Concepcion', 'Chateauroux', 'Sannois', 'H. Akko', 'Kawasaki Frontale', 'ChangchunYatai', 'Shanghai United', 'Boca Juniors', 'FC Gueugnon', 'EO Sidi Bouzid', 'MSV Duisburg', 'Matsumoto', 'Melbourne Knights', 'Queen of the South', 'Operario', 'LB Chateauroux', 'Hakoah Ramat Gan', 'Mantova', 'Gillingham', 'Ternana', 'Strasbourg', 'Brighton', 'Catanzaro', 'Novara', 'Siirt Jet-PA', 'Freiburg', 'Antalyaspor', 'San Martin S. J.', 'Oran', 'ES Beni-Khalled', 'Cassis-Carnoux', 'CD Universidad Catolica', 'FK Chita', 'Arbroath', 'Zhejiang Lucheng', 'JS Saoura', 'Deportivo Italia', 'ADO Den Haag', 'Levante', 'Olympique de Khouribga', 'Malatyaspor', 'Malaga', 'Solihull', 'Jaen', 'Gueugnon', 'St Johnstone', 'Maccabi Tel Aviv', 'Cannes', 'Esporte Clube Bahia', 'Gazovik Orenburg', 'Union Berlin', 'Chertanovo M.', 'Darlington', 'Red Diamonds', 'UA Maracaibo', 'USM Annaba', 'Lokomotiv Nizhni Novgorod', 'Xiamen Lanshi', 'Brondby', 'Servette Geneve', 'Everton', 'IF Elfsborg', 'Monza', 'Nueva Chicago', 'Ingolstadt', 'Roeselare', 'Excelsior', 'TianjinQuanjian', 'Sichuan Guancheng', 'Goias Esporte Clube', 'Melbourne Victory', 'Atletico Clube Goianiense', 'Midtjylland', 'Hartberg', 'Carolina RailHawks', 'Angers SCO', 'FC Pau', 'Reading', 'Peterhead', 'Besiktas', 'Doxa Dramas', 'Shanghai SIPG', 'Dagenham and Redbridge', 'SPAL Ferrara', 'Chicago Fire', 'RC Arbaa', 'SC Chabab Mohammedia', 'Almeria', 'Ajaccio GFCO', 'Como', 'Nanchang Hengyuan', 'DRB Tadjenanet', 'Manisaspor', 'Mlila', 'Houston Dynamo', 'JS Kasba Tadla', 'Brest', 'Paderborn', 'AC Barnechea', 'Germinal', 'Alverca', 'Hapoel Beer Sheva', 'Santander', 'Landskrona BoIS', 'Athletico Madrid', 'Monarcas Morelia', 'Trujillanos FC', 'Mouscron-Peruwelz', 'Valenciennes', 'MCAlger', 'Bucaspor', 'Tasman United', 'GE Brasil Pelotas', 'Mainz 05 II', 'Tondela', 'Newcastle United', 'Akademisk', 'Oeste FC', 'Cerezo Osaka', 'Clube de Regatas Brasil', 'San Luis FC', 'Alanyaspor', 'Zaragoza', 'Sao Caetano', 'Aragua FC', 'Lamia', 'Virtus Lanciano', 'Molenbeek', 'JiangsuSuning', 'Halmstads BK', 'Maccabi Herzliya', 'Sevilla FC B', 'Nosta Novotroitsk', 'Toulouse', 'Deportes Temuco', 'Lyngby', 'Tucanes FC', 'Fleetwood Town', 'Chabab Atlas Khenifra', 'Deportivo Anzoategui', 'Puebla FC', 'Vegalta Sendai', 'Sheffield Wednesday', 'Boston', 'Rennes', 'Rayo Majadahonda', 'FC Neftekhimik', 'Difaa Jadida', 'Liaoning', 'Fluminense Rio de Janeiro', 'Herfolge', 'CA Batna', 'FK Zhemchuzhina', 'ES Sahel', 'Helsingor', 'Sagan Tosu', 'Vendsyssel', 'Cambuur', 'Mjallby AIF', 'Brisbane Roar', 'Independiente del Valle', 'Cruz Azul', 'Eastern Suburbs', 'Brisbane Strikers', 'Brechin City', 'Jacksonville Armada', 'Lobos BUAP', 'Sampdoria', 'Thrasyvoulos', 'Sibir Novosibirsk', 'Konyaspor', 'Kotkan Tyovaen Palloilijat', 'Partick Thistle', 'Trelleborgs FF', 'USM Blida', 'GuizhouZhicheng', 'Valerenga IF', 'Lorca', 'Wolverhampton', 'US Creteil', 'Villarreal', 'Municipal Iquique', 'Minnesota', 'Siegen', 'San Luis', 'Anjalankoski', 'Fortuna Koln', 'Tottenham Hotspur', 'GuangzhouR&F', 'Ascoli', 'Rushden and Diamonds', 'Paris FC', 'AIK Solna', 'Cagliari', 'Woking', 'Thespakusatsu', 'Ironi Kiryat Shmona', 'Santa Cruz FC', 'Liverpool', 'Larisa', 'Internazionale Milano', 'Athletico Marseille', 'FK Nizhniy Novgorod', 'America RN', 'Sydney Olympic', 'Karlsruher SC', 'Atlas Guadalajara', 'Flamengo Rio de Janeiro', 'Murcia', 'PAOK', 'Avangard Kursk', 'Saarbrucken', 'Anderlecht', 'Alcoyano', 'Dijon', 'Blackpool', 'AS Sale', 'US Boulogne', 'St Albans', 'Pumas de la UNAM', 'Dinamo Moscow', 'Clyde', 'Plymouth Argyle', 'Exeter City', 'Lugo', 'CS Hammam-Lif', 'Martigues', 'CD Provincial Osorno', 'Osasuna', 'Red Star', 'Lokeren', 'Silkeborg', 'Seinajoki', 'Maccabi Haifa', 'Raja Casablanca', 'Dartford', 'Fortaleza', 'Panthrakikos', 'Maidstone', 'Diyarbakirspor', 'Montpellier', 'Beijing Hyundai', 'Avispa', 'Antwerp', 'Kashima Antlers', 'Chemnitzer FC', 'Hassania US Agadir', 'Istres', 'Ryukyu', 'Pacos Ferreira', 'Shanghai Greenland', 'Basaksehir', 'Daejeon Citizen', 'Waasland-Beveren', 'Khimik Dzerzhinsk', 'Dundee United', 'Carpi', 'PSV Eindhoven', 'Atletico Paranaense', 'Ittihad Tanger', 'GuangzhouEvergrande', 'Jubilo Iwata', 'Montedio Yamagata', 'Reutlingen', 'KFC Uerdingen', 'Dordrecht', 'Paysandu SC', 'Norwich City', 'Gainare Tottori', 'Yanbian FC', 'Estoril', 'Mansfield Town', 'Hacken', 'Northwich', 'Bury', 'Fagiano', 'FK Krasnodar', 'Malaga B', 'Curico Unido', 'Grays', 'San Francisco Deltas', 'Samsunspor', 'MC El Eulma', 'Clermont', 'Viking Stavanger', 'Neuchatel Xamax', 'Sturm Graz', 'Malmo FF', 'Mallorca', 'Oostende', 'Maritzburg Classic', 'Chippa United', 'Graafschap', 'Hapoel Acre FC', 'Arsenal Sarandi', 'Real Sociedad', 'Gwangju FC', 'Gil Vicente', 'San Lorenzo', 'Guangzhou Rich and Force', 'Sivasspor', 'Puerto Rico FC', 'Barnet', 'Iraklis', 'Zwickau', 'Jeonbuk FC', 'Chunnam Dragons', 'Empoli', 'Kansas City Wizards', 'Vestsjalland', 
           'Leverkusen', 'Preston North End', 'AS Beziers', 'Greuther Furth', 'Real Esppor Club', 'Yokohama Marinos', 'Horsens', 'Vila Nova FC GO', 'Arezzo', 'Panahaiki', 'Kalamaria', 'Oldham Athletic', 'Beijing Guoan', 'US Luzenac', 'FC Basel', 'Newcastle United Jets', 'Ionikos', 'Otago United', 'Arsenal', 'Rapide Oued Zem', 'AC Lala FC', 'Vallecano', 'LDU Quito', 'Antofagasta', 'Le Mans', 'Maghrib de Fes', 'Molde FK', 'Santa Clara', 'Union San Felipe', 'Tours', 'Egaleo', 'Indios Juarez', 'Nantes', 'JEF United', 'Shrewsbury Town', 'Brescia', 'Dunfermline Athletic', 'Go Ahead Eagles', 'Nimes Olympique', 'FK Radian-Baikal Irkutsk', 'Boreham Wood', 'Erciyesspor', 'FK Angusht Nazran', 'Hoffenheim', 'Elgin City', 'Thanda Royal Zulu', 'Batna', 'Daegu FC', 'Hapoel Tel Aviv', 'Club Brugge', 'Brasiliense', 'Portsmouth', 'Club Necaxa', 'Aldershot', 'Chesterfield', 'Stafford Rangers', 'Ajax Amsterdam', 'CD Chivas', 'Orleans', 'RW Ahlen', 'Ebbsfleet', 'Kerkyra', 'AS Marsa', 'Bnei Sachnin FC', 'Valencia', 'ES Hammam Sousse', 'Wolfsburg', 'TianjinTeda', 'Bnei Yehuda Tel Aviv', 'MSP Batna', 'Fakel Voronezh', 'Kickers Offenbach', 'Hannover 96', 'Tromso IL', 'Chelsea', 'ShandongLuneng', 'Frosinone', 'Canvey Island', 'Xanthi', 'Roasso Kumamoto', 'Olympique du Kef', 'Club Irapuato', 'Gremio Porto Alegre', 'Kouvola', 'Elazigspor', 'Atlanta Silverbacks', 'New Zealand Knights', 'YoungHeart Manawatu', 'Aviron Bayonnais', 'Utrecht', 'Bordeaux', 'Kaiserslautern', 'Sporting Gijon', 'Mordovia Saransk', 'Mushuc Runa', 'Fenerbahce', 'Heusden Zolder', 'Raith Rovers', 'Beveren', 'Monaco', 'Rimini', 'Gremio Prudente', 'Sevilla Atletico', 'EA Guingamp', 'Olympique Medea', 'Syrianska FC', 'Caroni FC', 'Hawkes Bay United FC', 'Uralan Elista', 'Granada', 'Belgrano Cordoba', 'Queens Park', 'Cape Town City FC', 'ES Metlaoui', 'Las Palmas', 'Sandefjord Fotball', 'Wuhan Zall FC', 'Internacional', 'Messina', 'Deportivo La Guaira', 'Arsenal Tula', 'Athinaikos', 'Roma', 'Leeds United', 'CA Bordj Bou Arreridj', 'AS Lyon-Duchere', 'Gap FC', 'Gateshead', 'Hartlepool', 'FF Jaro', 'Sanfrecce', 'Ulsan Hyundai', 'Waregem', 'Metropolitanos FC', 'SuperSport United', 'Higgins', 'Rosario Central', 'Derby County', 'FC Gifu', 'Libourne', 'Ravenna', 'Toronto FC', 'HavantW', 'Atalanta', 'Xerez', 'Dortmund II', 'Gefle IF', 'St Truiden', 'Braintree Town', 'Sydney FC', 'Stockport', 'Atletico Celaya', 'Kilmarnock', 'Tubize', 'Leyton Orient', 'Hamilton Wanderers', 'Esperance Zarzis', 'Melbourne City FC', 'Biskra', 'Mineros de Guayana', 'Brentford', 'Randers FC', 'Chamois Niortais', 'Chapecoense', 'FC Rouen', 'Pistoiese', 'Piacenza', 'Columbus Crew', 'Mamelodi Sundowns', 'MVD Rossii', 'Eibar', 'Jendouba Sport', 'Bari 1908', 'Tamworth', 'Sangju Sangmu', 'Harrogate', 'Zulia FC', 'Auckland Football Kingz', 'ASO Chlef', 'New York City FC', 'RB Salzburg', 'Wycombe Wanderers', 'Wiener Neustadt', 'Independiente', 'Akhisar Belediyespor', 'Panionios', 'Vancouver Whitecaps', 'Mogi Mirim', 'Luverdense', 'Atletico Socopo', 'FC Aarau', 'Leones Negros', 'Torpedo Vladimir', 'Caen', 'AS Khroub', 'Golden Arrows', 'CA Colon', 'GyE Jujuy', 'Esporte Clube Juventude', 'Icasa', 'Ranheim', 'Droylsden', 'Celta de Vigo', 'JS Kairouan', 'Hamilton Academical', 'St Etienne', 'Varen Nagasaki', 'Bradford', 'CA Bizertin', 'La Palme Tozeur', 'Reus Deportiu', 'Wacker Burghausen', 'Brommapojkarna', 'Estrella Roja', 'Galatasaray', 'Cercle Brugge', 'Osmanlispor', 'Argentinos Juniors', 'Pacy Vallee', 'Udinese', 'Enkopings', 'Portland Timbers', 'Sporting Kansas City', 'Kallithea', 'Harelbeke', 'Haka Valkeakoski', 'RC Kouba', 'Hallescher FC', 'Los Angeles FC', 'Macara', 'Seattle Sounders', 'Paradou AC', 'LDU Portoviejo', 'Rotor Volgograd', 'SCR Altach', 'JSM Bejaia', 'Livorno', 'Hameenlinna', 'Kickers Emden', 'Helsingborgs IF', 'Youssoufia Berrechid', 'Charlton Athletic', 'AS Cannes', 'Club Africain', 'Ironi Ramat HaSharon', 'Montrose', 'Benfica', 'Genclerbirligi', 'Hapoel Kfar Saba', 'Miami FC', 'Alloa Athletic', 'Colorado Rapids', 'Goztep', 'RC Relizane', 'Erzurumspor', 'Morecambe', 'Estrela Amadora', 'Modena', 'Munich 1860', 'Sarpsborg 08', 'Stromsgodset IF', 'US Ben Guerdane', 'Wollongong City Wolves', 'Cholet', 'Ehime FC', 'Medea', 'Ittihad Khemisset', 'KAC de Kenitra', 'New England Revolution', 'IFK Mariehamn', 'West Ham United', 'Guizhou Zhicheng', 'Barcelona SC', 'Histon', 'Watford', 'Virtus Entella', 'Parramatta Power', 'Numancia', 'NA Hussein Dey', 'Spezia', 'Ethnikos Asteras', 'Bursaspor', 'Charleroi', 'Elche', 'SC Ashdod', 'Mechelen', 'Ciudad de Murcia', 'Leonesa', 'Kocaelispor', 'Rochdale', 'Foggia', 'Shandong Luneng', 'Fylde', 'Bragantino', 'Berwick Rangers', 'West Bromwich Albion', 'CA Temperley', 'Qingdao', 'Torquay', 'Schwarz Weiss Bregenz', 'Yaracuyanos FC', 'Aston Villa', 'Deportivo Toluca', 'Ipatinga FC', 'FK Saturn', 'PK35 Vantaa', 'Ferrol', 'BeijingGuoan', 'Catania', 'Adanaspor', 'Huddersfield Town', 'RC Strasbourg', 'Kalmar FF', 'Deportivo Azogues', 'Volga Nizhniy Novgorod', 'Wuppertaler SV', 'Stade Tunisien', 'Olympic Sharks', 'Coquimbo Unido', 'SV Grodig', 'Ottawa Fury', 'Dalian Aerbin', 'Tiro Federal Rosario', 'Ergotelis', 'US Quevilly', 'Luch-Energia', 'Southern United', 'ChongqingLifan', 'BidVest Wits', 'FC Edmonton', 'Kettering Town', 'Weymouth', 'Relizane', 'TPS Turku', 'Portuguesa', 'Perth Glory', 'Joinville Esporte Clube', 'Audax Italiano', 'Bristol City', 'HusseinDey', 'Fiorentina', 'Yiannina', 'Everton CD', 'Suwon Bluewings', 'Gold Coast United', 'Louhans-Cuiseaux', 'Krylia Sovetov', 'Dorados de Sinaloa', 'Chernomorets Novorossisk', 'HollyHock', 'CF Atlante', 'Aldosivi', 'Roda', 'St Pauli', 'USM Bel Abbes', 'Ross County', 'Tigre', 'Le Poire-sur-Vie', 'FC Ashdod', 'Hapoel Hadera', 'Monchengladbach', 'Esperance Tunis', 'Bodo/Glimt', 'Stuttgarter Kickers', 'Glasgow Rangers', 'Jeonnam Dragons', 'San Jose Earthquakes', 'Odense', 'JS El Massira', 'USL Dunkerque', 'FC Innsbruck', 'Hertha Berlin', 'Istanbulspor', 'Viikingit', 'Bergen', 'Stade Plabennec', 'Wrexham', 'Rostselmash Rostov', 'Wigan Athletic', 'ES Setif', 'Los Andes', 'Deportivo Quevedo', 'Portogruaro', 'Portimonense', 'Salyut-Energiya Belgorod', 'Nacional', 'Scunthorpe United', 'Grimsby', 'Stabaek IF', 'Olimpo', 'AS Cherbourg', 'Osnabruck', 'Club Almagro', 'Western Sydney Wanderers', 'Lorient', 'Sporting Braga', 'Cardiff City', 'Barcelona B', 'Gallos Blancos Queretaro FC', 'Sassuolo', 'Maritzburg United', 'Middlesbrough', 'Kaizer Chiefs', 'Hapoel Rishon', 'Panetolikos', 'Aalesunds FK', 'Bath City', 'Salamanca', 'Swansea City', 'Deportivo Cuenca', 'Kongsvinger IL', 'FC Luzern', 'Vitesse', 'El Nacional', 'Osters IF', 'Southend', 'Gravesend', 'Orduspor', 'ABC FC', 'Guiseley', 'Patronato', 'LDU Loja', 'FK Kamaz', 'Kapfenberger SV', 'Aalen', 'Omiya Ardija', 'Stoke City', 'Puerto Montt', 'Penafiel', 'CA Lanus', 'Chengdu Blades', 'Maccabi Ahi Nazareth', 'Hapoel Ramat Gan', 'Union La Calera', 'Hacettepespor', 'Ankaraspor', 'EGS Gafsa', 'Wurzburger Kickers', 'Shanghai Shenxin', 'Olympique Beja', 'Minerven FC', 'Airdrie United', 'Hapoel Nazareth', 'FC Salyut Belgorod', 'Rayo Oklahoma City', 'Bolton', 'Bayern Munich', 'Wanderers SC', 'Girona', 'Mjondalen IF', 'San Antonio Scorpions', 'WA Tlemcen', 'CF Pachuca', 'US Concarneau', 'Chongqing Lifan', 'CD Huachipato', 'Nottingham Forest', 'USM El Harrach', 'Magdeburg', 'Greenock Morton', 'Nordsjalland', 'Burgos', 'Hapoel Ashkelon', 'Busan IPark', 'Auxerre', 'Sevilla FC', 'Birmingham City', 'Grenoble', 'Koblenz', 'Duque de Caxias', 'AEK', 'GIF Sundsvall', 'Criciuma Esporte Clube', 'Southport', 'Huesca', 'CR Belouizdad', 'Deportivo Lara', 'Sokol Saratov', 'Quilmes AC', 'Northern Spirit', 'CSA', 'Padova', 'Mouloudia Oujda', 'Academica', 'Bologna', 'Zweigen', 'Shijiazhuang Ever Bright', 'FC Koln', 'Cuiaba Esporte', 'ESTAC Troyes', 'UJA Alfortville', 'Gamba Osaka', 'Platinum Stars', 'Kemi Kings', 'Sampaio Correa FC', 'Kyoto Sanga', 'Telford United', 'RW Erfurt', 'Colo Colo', 'FC Tokyo', 'FK Moscow', 'Puerto Cabello', 'Atvidabergs', 'NAC Breda', 'RW Essen', 'Siena', 'Rubin Kazan', 'Polokwane City', 'Farense', 'Lens', 'IFK Goteborg', 'Guadalajara', 'Sonnenhof Grossaspach', 'For Sittard', 'Yunnan Hongta', 'Estudiantes', 'Salgueiro AC', 'Los Angeles Galaxy', 'Mainz 05', 'Zenit St Petersburg', 'Yverdon Sport', 'Vissel Kobe', 'East Stirling', 'AS Kasserine', 'Sporting Lisbon', 'Rovaniemi PS', 'Jonkopings Sodra', 'Arouca', 'Accrington', 'SKA-Energia Khabarovsk', 'Atletico San Luis', 'Livingston', 'Honefoss BK', 'Milton Keynes Dons', 'ASM Oran', 'Venezia', 'Terrassa', 'Oulu', 'Gaziantepspor', 'Agremiacao Sportiva Arapiraquense', 'Juve Stabia', 'Dinamo Bryansk', 'MO Bejaia', 'Wuhan Optics Valley', 'Maidenhead', 'Vendee Lucon', 'Wolfsberger AC', 'Club Tijuana', 'America de Quito', 'Celtic Glasgow', 'Hayes and Yeading', 'Zamora FC', 'LASK Linz', 'Hyde United', 'Brann Bergen', 'Reggina', 'MC Alger', 'Feyenoord Rotterdam', 'Giannina', 'Real Union', 'Stade Gabesien', 'Veria', 'Eastleigh', 'Marconi-Fairfield Stallions', 'Shanghai East Asia', 'Philadelphia Union', 'Nocerina 1910', 'Pohang Steelers', 'AS Gabes', 'US Tataouine', 'Walsall', 'Lille', 'Chaves', 'CSKA Moscow', 'Vicenza', 'Sedan', 'All Boys', 'Orgryte IS', 'Wellington Phoenix R', 'Yozgatspor', 'Racing Club', 'US Colomiers', 'Tianjin Teda', 'South Melbourne Lakers', 'Oviedo', 'KPV Kokkola', 'Sandnes Ulf', 'Gallipoli', 'Estudiantes Tecos', 'FC Vaduz', 'Botafogo Rio de Janeiro', 'Ayr United', 'Union de Santa Fe', 'Hereford', 'San Marcos de Arica', 'Alicante', 'Wellington Phoenix', 'Hull City', 'Sabadell', 'FC Brussels', 'Rouen', 'Sakaryaspor', 'Alemannia Aachen', 'Macclesfield', 'Young Boys', 'Jeju United', 'Eupen', 'RB Leipzig', 'Tecnico Universitario', 'St Raphael FC', 'Inter Turku', 'Chester', 'Aarhus', 'Cartagena', 'Tecos FC', 'Kasimpasa', 'Balikesirspor', 'Union Espanola', 'Sete', 'Espoli', 'Le Havre', 'Denizlispor', 'Granada 74', 'Valladolid', 'Kortrijk', 'Kayserispor', 'Salernitana', 'Benevento', 'Ventforet Kofu', 'Shaanxi Lijun Guoli', 'Vannes OC', 
    'CS Constantine', 'Sirius', 'FSV Frankfurt', 'Algeciras', 'Athletic Bilbao B', 'Chacarita Juniors', 'Rio Ave', 'Hercules', 'Waalwijk', 'Peterborough United', 'CA Bastia', 'JA Drancy', 'Tampa Bay Rowdies', 'Uniao Madeira', 'Vecindario', 'Yanbian', 'Naval', 'Tenerife', 'Torino', 'Kuban Krasnodar', 'Beira Mar', 'Sheffield United', 'Shimizu Pulse', 'Montreal Impact', 'Renofa Yamaguchi', 'Olympiakos Piraeus', 'Indy Eleven', 'CS Sedan', 'Feirense', 'Dender', 'Recreativo', 'Swindon Town', 'AmaZulu', 'Adelaide City Force', 'Veracruz Sporting Club', 'FK Rostov', 'Sutton United', 'Dumbarton', 'SR Colmar', 'Harrach', 'FC Tambov', 'Deportivo Petare', 'Llaneros de Guanare', 'Valence', 'Moghreb de Tetouan', 'FC Dundee', 'SonderjyskE', 'Eintracht Frankfurt', 'Jokerit Helsinki', 'Jaguares Chiapas', 'FC Thun', 'Real Madrid B', 'Ostersunds FK', 'Queensland Roar', 'St Polten', 'Parma', 'Jiangsu Suning', 'Pisa', 'OMR El Annasser', 'Manta FC', 'Mirandes', 'Incheon United', 'La Serena', 'Deportivo Guadalajara', 'TP47 Tornio', 'Nice', 'US Monastir', 'Llagostera', 'FC Metz', 'Yokohama FC', 'Doncaster Rovers', 'Gangwon FC', 'FAR de Rabat', 'Oxford United', 'Sochaux', 'Bellinzona', 'Extremadura', 'Oita Trinita', 'Velez Sarsfield', 'Tadjenant', 'Port Vale', 'CF Monterrey', 'Paris Saint-Germain', 'Besancon', 'Ankaragucu', 'Clydebank', 'Stenhousemuir', 'Helsingfors IFK', 'HenanJianye', 'IFK Norrkoping', 'Frem Kobenhavn', 'FC Wil', 'Farsley', 'Elversberg', 'Campomaiorense', 'Dynamo Dresden', 'Universidad de Concepcion', 'Energie Cottbus', 'Vaasan PS', 'Burnley', 'Seongnam FC', 'Hobro', 'Engen Santos FC', 'Alania Vladikavkaz', 'Team Wellington', 'Wimbledon', 'Hamburger SV', 'Eastern Pride', 'Eastbourne Borough', 'Castellon', 'Racing Besancon', 'La Coruna', 'Burton', 'Albacete', 'Defensa y Justicia', 'ShanghaiSIPG', 'Estudiantes de Caracas', 'Westerlo', 'Tranmere', 'Boa Esporte Clube', 'Beijing Renhe FC', 'Niki Volou FC', 'Lyn Oslo', 'SV Mattersburg', 'Sao Bento', 'Forest Green', 'Dinamo St Petersburg', 'Luton Town', 'Vastra Frolunda', 'FC Chambly', 'Wehen Wiesbaden', 'Proodeftiki', 'Notts County', 'Deportivo Nublense', 'Universidad Catolica', 'CR Vasco da Gama', 'Terek Grozny', 'Santiago Wanderers', 'SD Aucas', 'Erzgebirge Aue', 'Sunderland', 'Rapid Wien', 'Aalst', 'Badajoz', 'RAC Casablanca', 'Highlands Park', 'Anzhi Makhachkala', 'FUS de Rabat', 'VVV Venlo', 'Lausanne Sport', 'Mouscron', 'Leiria', 'Belenenses', 'Queens Park Rangers', 'AS Djerba', 'FC Dallas', 'Gimnastic Tarragona', 'Lubeck', 'Heracles', 'Guaros de Lara', 'ShanghaiShenhua', 'Hammarby IF', 'Leixoes', 'Olympique de Safi', 'Fuerza Amarilla Machala', 'Union Lara', 'FC Lahti', 'Orlando City', 'Adelaide United', 'Canberra Cosmos', 'Dortmund', 'Yeovil Town', 'Sparta Rotterdam', 'River Plate', 'FC Martigues', 'Setubal', 'Sogndal IL', 'Vasco da Gama', 'Unterhaching', 'Rosenborg Trondheim', 'Olhanense', 'MC Saida', 'Laval', 'FK Haugesund', 'AZ Alkmaar', 'Manchester City', 'Karabukspor', 'Manchester United', 'Nurnberg', 'FC Schaffhausen', 'Guingamp', 'Zwolle', 'Cruzeiro Esporte Clube', 'Real Madrid', 'St Mirren', 'Bochum', 'OFI Heraklion', 'Olympique Marseille', 'Avellino', 'Atletico Venezuela', 'Jahn Regensburg', 'FC Istres', 'Babelsberg', 'Beitar Jerusalem', 'Carlisle', 'Manning Rangers', 'Varzim', 'Leicester City', 'HB Koge', 'Ponte Preta', 'Dalkurd', 'Bush Bucks', 'FC Ufa', 'Sociedade Esportiva Palmeiras', 'Northampton Town', 'Portuguesa FC', 'VfB Stuttgart II', 'Lincoln', 'Sport Club Recife', 'Latina', 'Saoura', 'FC Zurich', 'Lecce', 'Cheltenham', 'Varese', 'USMAlger', 'Wasquehal', 'Talleres Cordoba', 'Alcorcon', 'Hansa Rostock', 'KooTeePee', 'MC Oran', 'CD Godoy Cruz', 'COD Meknes', 'Juventus', 'Auckland City FC', 'MOBejaia', 'Saturn-REN TV', 'Gyeongnam FC', 'FC Sakhalin', 'Albirex', 'Sandhausen', 'Admira Wacker', 'Fredrikstad FK', 'FC Emmen', 'FC Honka', 'Londrina Esporte Clube', 'Irtysh Omsk', 'Ipswich Town', 'Barrow', 'Atletico Tucuman', 'AS Beauvais', 'Atletico Rafaela', 'SC Imbabura', 'Cuernavaca', 'Mersin Idman Yurdu', 'Wydad AC', 'Deportivo Zulia', 'Trofense', 'Changsha Ginde', 'Renaissance de Berkane', 'FC Sion', 'Stevenage', 'Cosenza', 'JSKabylie', 'Akcaabat Sebatspor', 'Crewe Alexandra', 'Djurgardens', 'Gent', 'USM Alger', 'Evian Thonon Gaillard', 'Xiamen Xiaxin', 'Annan Athletic', 'Gubbio', 'Paniliakos', 'Salford', 'CS Emelec', 'Lierse', 'CR Al Hoceima', 'Kataller Toyama', 'Chiapas FC', 'Austria Wien', 'ES Uzes Pont du Gard', 'Sao Paulo FC', 'Lommel', 'Metallurg-Kuzbass Novokuznetsk', 'CA Banfield', 'Vityaz Podolsk', 'Villarreal B', 'Clube Nautico', 'Napoli', 'Bournemouth', 'Mannheim', 'Welling United', 'FK Ural', 'Alaves')

dataFrameHome= pd.DataFrame(listHome)
df = dataFrameHome.reset_index()
dfH= df.rename(columns={'index': 'label', 0:"team"})
dictionary_Teams = dict(zip(dfH.team.unique(), dfH.label.unique(), ))  #create a dictionary 
dictionary_Teams

{'Fulham': 0,
 'Darmstadt 98': 1,
 'Odd Grenland': 2,
 'Troyes': 3,
 'Fort Lauderdale Strikers': 4,
 'Maccabi Netanya': 5,
 'Sportfreunde Lotte': 6,
 'Athletic Bilbao': 7,
 'Zhejiang Yiteng': 8,
 'Newells Old Boys': 9,
 'Hamarkameratene': 10,
 'Jazz Pori': 11,
 'Consadole Sapporo': 12,
 'Espanyol Barcelona': 13,
 'Macae Esporte FC': 14,
 'Boavista': 15,
 'Ponferradina': 16,
 'Cowdenbeath': 17,
 'Kuopion PS': 18,
 'Pescara': 19,
 'Altay': 20,
 'Eintracht Trier': 21,
 'Belouizdad': 22,
 'Tigres de la Universidad Autonoma': 23,
 'Instituto Cordoba': 24,
 'Bourg Peronnas': 25,
 'Platanias': 26,
 'Triestina': 27,
 'HJK Helsinki': 28,
 'Rodez AF': 29,
 'CO Medenine': 30,
 'Santos FC': 31,
 'FC Seoul': 32,
 'Beijing Sanyaun': 33,
 'North Ferriby': 34,
 'Olympique Lyonnais': 35,
 'Real Salt Lake': 36,
 'Suwon City FC': 37,
 'Levadeiakos': 38,
 'FK Amkar Perm': 39,
 'River Ecuador': 40,
 'KagoshimaUtd': 41,
 'Deportes Melipilla': 42,
 'Southampton': 43,
 'Hapoel Raanana': 44,
 'Central Coast Mariners': 45,
 'GAIS Goteborg': 46,
 'Crystal Palace': 47,
 'Atromitos': 48,
 'Panserraikos': 49,
 'East Fife': 50,
 'Gwangju Sangmu': 51,
 'Jomo Cosmos': 52,
 'Hangzhou Greentown': 53,
 'ASM Belfort': 54,
 'Fortuna Dusseldorf': 55,
 'Cordoba': 56,
 'Tampere United': 57,
 'Schalke 04': 58,
 'Delemont': 59,
 'Hellas Verona': 60,
 'Dalian Haichang': 61,
 'Ceara SC': 62,
 'Heerenveen': 63,
 'FC Villefranche': 64,
 'AC Milan': 65,
 'Start Kristiansand': 66,
 'Esporte Clube Vitoria BA': 67,
 'Arles': 68,
 'Panathinaikos': 69,
 'Aberdeen': 70,
 'Lokomotiv Moscow': 71,
 'Marseille Consolat': 72,
 'Stranraer': 73,
 'Cesena': 74,
 'Real Betis': 75,
 'Chalkidona': 76,
 'Silver Stars': 77,
 'Shinnik Yaroslavl': 78,
 'Genoa': 79,
 'Shonan Bellmare': 80,
 'Kawkab AC Marrakech': 81,
 'Figueirense': 82,
 'Sarmiento de Junin': 83,
 'Salgueiros': 84,
 'De Graafschap': 85,
 'Barcelona': 86,
 'Bloemfontein Celtic': 87,
 'Allianssi': 88,
 'Santiago Morning': 89,
 'Hapoel Petach-Tikva': 90,
 'Olympiakos Volou': 91,
 'AlbinoLeffe': 92,
 'Tochigi SC': 93,
 'FK Khimki': 94,
 'BelAbbes': 95,
 'AFC Eskilstuna': 96,
 'Baltika Kaliningrad': 97,
 'North Queensland Fury': 98,
 'Avai FC': 99,
 'Lota Schwager': 100,
 'Salisbury': 101,
 'Edinburgh City': 102,
 'Aalborg': 103,
 'Black Leopards': 104,
 'Augsburg': 105,
 'Braunschweig': 106,
 'D.C. United': 107,
 'Guangzhou Evergrande': 108,
 'Holstein Kiel': 109,
 'Crawley Town': 110,
 'Meppen': 111,
 'Urena Sport Club': 112,
 'Kidderminster': 113,
 'Inverness CT': 114,
 'Millwall': 115,
 'Hibernian': 116,
 'Enisey Krasnoyarsk': 117,
 'Baroka FC': 118,
 'Cremonese': 119,
 'Giravanz': 120,
 'FC Lugano': 121,
 'WaiBOP United': 122,
 'New York Red Bulls': 123,
 'Canterbury United': 124,
 'Tianjin Quanjian': 125,
 'Chievo Verona': 126,
 'Carl Zeiss Jena': 127,
 'Vejle': 128,
 'Tupi FC': 129,
 'Moroka Swallows': 130,
 'New York Cosmos': 131,
 'FC Superfund': 132,
 'Guaratingueta': 133,
 'Bromley': 134,
 'Tuks FC': 135,
 'Grazer AK': 136,
 'SC Bastia': 137,
 'FK Tyumen': 138,
 'Free State Stars': 139,
 'Den Bosch': 140,
 'Falkenbergs': 141,
 'UD Las Palmas': 142,
 'CD Cobreloa': 143,
 'Hyeres FC': 144,
 'Aris': 145,
 'FC Karnten': 146,
 'Cambridge': 147,
 'Trabzonspor': 148,
 'NEC Nijmegen': 149,
 'Atlanta United FC': 150,
 'Carquefou JA': 151,
 'Bayern Munich II': 152,
 'Machida Zelvia': 153,
 'Leganes': 154,
 'Americana Futebol': 155,
 'Newport County': 156,
 'Schweinfurt': 157,
 'Grasshoppers Zurich': 158,
 'FK Tosno': 159,
 'Scarborough': 160,
 'Altrincham': 161,
 'Caracas FC': 162,
 'Maccabi Petach-Tikva': 163,
 'Universidad de Chile': 164,
 'Compostela': 165,
 'Preussen Munster': 166,
 'AC Ajaccio': 167,
 'RW Oberhausen': 168,
 'Roosendaal': 169,
 'Club Leon': 170,
 'Torpedo Moscow': 171,
 'Albion Rovers': 172,
 'America MG': 173,
 'Grombalia Sports': 174,
 'Trapani': 175,
 'Jyvaskyla': 176,
 'CD Cobresal': 177,
 'Lewes': 178,
 'Treviso': 179,
 'Aves': 180,
 'Cittadella': 181,
 'Colchester': 182,
 'Coritiba FC': 183,
 'Hearts': 184,
 'Crotone': 185,
 'Amiens SC': 186,
 'Club de Futbol America': 187,
 'Lazio': 188,
 'Blackburn Rovers': 189,
 'Marignane': 190,
 'GyE La Plata': 191,
 'Henan Jianye': 192,
 'Guimaraes': 193,
 'Cadiz': 194,
 'Setif': 195,
 'Carabobo FC': 196,
 'JS Kabylie': 197,
 'Nancy': 198,
 'Centro Italo': 199,
 'US Avranches': 200,
 'FC Volgar Astrakhan': 201,
 'Shenzhen FC': 202,
 'FK Torpedo Armavir': 203,
 'Genk': 204,
 'Esbjerg fB': 205,
 'AFC Wimbledon': 206,
 'EOG Kram': 207,
 'Groningen': 208,
 'Stirling Albion': 209,
 'CSD Rangers': 210,
 'FC Kobenhavn': 211,
 'Sydney United Pumas': 212,
 'FC St Gallen': 213,
 'SAS Epinal': 214,
 'Kavala': 215,
 'FC Cincinnati': 216,
 'FK Tom Tomsk': 217,
 'Corinthians Paulista': 218,
 'Arminia Bielefeld': 219,
 'Moreirense': 220,
 'Pontevedra': 221,
 'Kamatamare': 222,
 'Standard': 223,
 'Porto': 224,
 'Asteras Tripolis': 225,
 'Wydad de Fes': 226,
 'Nimes': 227,
 'Poli Ejido': 228,
 'Bristol Rovers': 229,
 'Santos Laguna': 230,
 'Deportivo Tachira': 231,
 'Raja Beni Mellal': 232,
 'Tokushima Vortis': 233,
 'SV Ried': 234,
 'Spartak Nalchik': 235,
 'Ljungskile SK': 236,
 'Sochi': 237,
 'Palermo': 238,
 'Orlando Pirates': 239,
 'Eskisehirspor': 240,
 'VfB Stuttgart': 241,
 'Falkirk': 242,
 'Changchun Yatai': 243,
 'Atletico El Vigia': 244,
 'Ancona 1905': 245,
 'CRB Ain Fakroun': 246,
 'Waikato FC': 247,
 'Hebei China Fortune FC': 248,
 'Stade de Reims': 249,
 'Willem II': 250,
 'Twente Enschede': 251,
 'Metallurg Lipetsk': 252,
 'Bucheon SK': 253,
 'Coventry City': 254,
 'Louvieroise': 255,
 'Ajax Cape Town': 256,
 'Gremio Barueri': 257,
 'Spartak Moscow': 258,
 'Parana Clube': 259,
 'Gretna': 260,
 'Nuneaton Town': 261,
 'Oud-Heverlee Leuven': 262,
 'Volendam': 263,
 'York City': 264,
 'Kallonis': 265,
 'Getafe': 266,
 'Atletico Mineiro': 267,
 'Halifax': 268,
 'Kashiwa Reysol': 269,
 'Alfreton Town': 270,
 'Waitakere United': 271,
 'Forfar Athletic': 272,
 'Hapoel Haifa': 273,
 'Perugia': 274,
 'Rotherham United': 275,
 'Ilves Tampere': 276,
 'Orebro SK': 277,
 'Kristiansund': 278,
 'CA San Martin': 279,
 'Guarani FC': 280,
 'Nagoya Grampus': 281,
 'Lleida': 282,
 'Dover Athletic': 283,
 'CD Palestino': 284,
 'Werder Bremen': 285,
 'Crucero del Norte': 286,
 'Santo Andre Esporte Clube': 287,
 'Lillestrom SK': 288,
 'Les Herbiers VF': 289,
 'Barnsley': 290,
 'Maritimo': 291,
 'Deportivo Quito': 292,
 'CD Olmedo': 293,
 'Akratitos': 294,
 'Pro Vercelli': 295,
 'AS Moulins': 296,
 'Club Sportif Sfaxien': 297,
 'Viborg': 298,
 'Heidenheim': 299,
 'Motherwell': 300,
 'Grosseto': 301,
 'Werder Bremen II': 302,
 'Tokyo Verdy': 303,
 'CD Clan Juvenil': 304,
 'Apollon': 305,
 'Assyriska': 306,
 'Constantine': 307,
 'August First Football Team': 308,
 'Huracan': 309,
 'Kalamata': 310,
 'Monagas': 311,
 'Hebei': 312,
 'Rizespor': 313,
 'San Martin Tucuman': 314,
 'Estudiantes de Merida': 315,
 'Delfin SC': 316,
 'Deportes Concepcion': 317,
 'Chateauroux': 318,
 'Sannois': 319,
 'H. Akko': 320,
 'Kawasaki Frontale': 321,
 'ChangchunYatai': 322,
 'Shanghai United': 323,
 'Boca Juniors': 324,
 'FC Gueugnon': 325,
 'EO Sidi Bouzid': 326,
 'MSV Duisburg': 327,
 'Matsumoto': 328,
 'Melbourne Knights': 329,
 'Queen of the South': 330,
 'Operario': 331,
 'LB Chateauroux': 332,
 'Hakoah Ramat Gan': 333,
 'Mantova': 334,
 'Gillingham': 335,
 'Ternana': 336,
 'Strasbourg': 337,
 'Brighton': 338,
 'Catanzaro': 339,
 'Novara': 340,
 'Siirt Jet-PA': 341,
 'Freiburg': 342,
 'Antalyaspor': 343,
 'San Martin S. J.': 344,
 'Oran': 345,
 'ES Beni-Khalled': 346,
 'Cassis-Carnoux': 347,
 'CD Universidad Catolica': 348,
 'FK Chita': 349,
 'Arbroath': 350,
 'Zhejiang Lucheng': 351,
 'JS Saoura': 352,
 'Deportivo Italia': 353,
 'ADO Den Haag': 354,
 'Levante': 355,
 'Olympique de Khouribga': 356,
 'Malatyaspor': 357,
 'Malaga': 358,
 'Solihull': 359,
 'Jaen': 360,
 'Gueugnon': 361,
 'St Johnstone': 362,
 'Maccabi Tel Aviv': 363,
 'Cannes': 364,
 'Esporte Clube Bahia': 365,
 'Gazovik Orenburg': 366,
 'Union Berlin': 367,
 'Chertanovo M.': 368,
 'Darlington': 369,
 'Red Diamonds': 370,
 'UA Maracaibo': 371,
 'USM Annaba': 372,
 'Lokomotiv Nizhni Novgorod': 373,
 'Xiamen Lanshi': 374,
 'Brondby': 375,
 'Servette Geneve': 376,
 'Everton': 377,
 'IF Elfsborg': 378,
 'Monza': 379,
 'Nueva Chicago': 380,
 'Ingolstadt': 381,
 'Roeselare': 382,
 'Excelsior': 383,
 'TianjinQuanjian': 384,
 'Sichuan Guancheng': 385,
 'Goias Esporte Clube': 386,
 'Melbourne Victory': 387,
 'Atletico Clube Goianiense': 388,
 'Midtjylland': 389,
 'Hartberg': 390,
 'Carolina RailHawks': 391,
 'Angers SCO': 392,
 'FC Pau': 393,
 'Reading': 394,
 'Peterhead': 395,
 'Besiktas': 396,
 'Doxa Dramas': 397,
 'Shanghai SIPG': 398,
 'Dagenham and Redbridge': 399,
 'SPAL Ferrara': 400,
 'Chicago Fire': 401,
 'RC Arbaa': 402,
 'SC Chabab Mohammedia': 403,
 'Almeria': 404,
 'Ajaccio GFCO': 405,
 'Como': 406,
 'Nanchang Hengyuan': 407,
 'DRB Tadjenanet': 408,
 'Manisaspor': 409,
 'Mlila': 410,
 'Houston Dynamo': 411,
 'JS Kasba Tadla': 412,
 'Brest': 413,
 'Paderborn': 414,
 'AC Barnechea': 415,
 'Germinal': 416,
 'Alverca': 417,
 'Hapoel Beer Sheva': 418,
 'Santander': 419,
 'Landskrona BoIS': 420,
 'Athletico Madrid': 421,
 'Monarcas Morelia': 422,
 'Trujillanos FC': 423,
 'Mouscron-Peruwelz': 424,
 'Valenciennes': 425,
 'MCAlger': 426,
 'Bucaspor': 427,
 'Tasman United': 428,
 'GE Brasil Pelotas': 429,
 'Mainz 05 II': 430,
 'Tondela': 431,
 'Newcastle United': 432,
 'Akademisk': 433,
 'Oeste FC': 434,
 'Cerezo Osaka': 435,
 'Clube de Regatas Brasil': 436,
 'San Luis FC': 437,
 'Alanyaspor': 438,
 'Zaragoza': 439,
 'Sao Caetano': 440,
 'Aragua FC': 441,
 'Lamia': 442,
 'Virtus Lanciano': 443,
 'Molenbeek': 444,
 'JiangsuSuning': 445,
 'Halmstads BK': 446,
 'Maccabi Herzliya': 447,
 'Sevilla FC B': 448,
 'Nosta Novotroitsk': 449,
 'Toulouse': 450,
 'Deportes Temuco': 451,
 'Lyngby': 452,
 'Tucanes FC': 453,
 'Fleetwood Town': 454,
 'Chabab Atlas Khenifra': 455,
 'Deportivo Anzoategui': 456,
 'Puebla FC': 457,
 'Vegalta Sendai': 458,
 'Sheffield Wednesday': 459,
 'Boston': 460,
 'Rennes': 461,
 'Rayo Majadahonda': 462,
 'FC Neftekhimik': 463,
 'Difaa Jadida': 464,
 'Liaoning': 465,
 'Fluminense Rio de Janeiro': 466,
 'Herfolge': 467,
 'CA Batna': 468,
 'FK Zhemchuzhina': 469,
 'ES Sahel': 470,
 'Helsingor': 471,
 'Sagan Tosu': 472,
 'Vendsyssel': 473,
 'Cambuur': 474,
 'Mjallby AIF': 475,
 'Brisbane Roar': 476,
 'Independiente del Valle': 477,
 'Cruz Azul': 478,
 'Eastern Suburbs': 479,
 'Brisbane Strikers': 480,
 'Brechin City': 481,
 'Jacksonville Armada': 482,
 'Lobos BUAP': 483,
 'Sampdoria': 484,
 'Thrasyvoulos': 485,
 'Sibir Novosibirsk': 486,
 'Konyaspor': 487,
 'Kotkan Tyovaen Palloilijat': 488,
 'Partick Thistle': 489,
 'Trelleborgs FF': 490,
 'USM Blida': 491,
 'GuizhouZhicheng': 492,
 'Valerenga IF': 493,
 'Lorca': 494,
 'Wolverhampton': 495,
 'US Creteil': 496,
 'Villarreal': 497,
 'Municipal Iquique': 498,
 'Minnesota': 499,
 'Siegen': 500,
 'San Luis': 501,
 'Anjalankoski': 502,
 'Fortuna Koln': 503,
 'Tottenham Hotspur': 504,
 'GuangzhouR&F': 505,
 'Ascoli': 506,
 'Rushden and Diamonds': 507,
 'Paris FC': 508,
 'AIK Solna': 509,
 'Cagliari': 510,
 'Woking': 511,
 'Thespakusatsu': 512,
 'Ironi Kiryat Shmona': 513,
 'Santa Cruz FC': 514,
 'Liverpool': 515,
 'Larisa': 516,
 'Internazionale Milano': 517,
 'Athletico Marseille': 518,
 'FK Nizhniy Novgorod': 519,
 'America RN': 520,
 'Sydney Olympic': 521,
 'Karlsruher SC': 522,
 'Atlas Guadalajara': 523,
 'Flamengo Rio de Janeiro': 524,
 'Murcia': 525,
 'PAOK': 526,
 'Avangard Kursk': 527,
 'Saarbrucken': 528,
 'Anderlecht': 529,
 'Alcoyano': 530,
 'Dijon': 531,
 'Blackpool': 532,
 'AS Sale': 533,
 'US Boulogne': 534,
 'St Albans': 535,
 'Pumas de la UNAM': 536,
 'Dinamo Moscow': 537,
 'Clyde': 538,
 'Plymouth Argyle': 539,
 'Exeter City': 540,
 'Lugo': 541,
 'CS Hammam-Lif': 542,
 'Martigues': 543,
 'CD Provincial Osorno': 544,
 'Osasuna': 545,
 'Red Star': 546,
 'Lokeren': 547,
 'Silkeborg': 548,
 'Seinajoki': 549,
 'Maccabi Haifa': 550,
 'Raja Casablanca': 551,
 'Dartford': 552,
 'Fortaleza': 553,
 'Panthrakikos': 554,
 'Maidstone': 555,
 'Diyarbakirspor': 556,
 'Montpellier': 557,
 'Beijing Hyundai': 558,
 'Avispa': 559,
 'Antwerp': 560,
 'Kashima Antlers': 561,
 'Chemnitzer FC': 562,
 'Hassania US Agadir': 563,
 'Istres': 564,
 'Ryukyu': 565,
 'Pacos Ferreira': 566,
 'Shanghai Greenland': 567,
 'Basaksehir': 568,
 'Daejeon Citizen': 569,
 'Waasland-Beveren': 570,
 'Khimik Dzerzhinsk': 571,
 'Dundee United': 572,
 'Carpi': 573,
 'PSV Eindhoven': 574,
 'Atletico Paranaense': 575,
 'Ittihad Tanger': 576,
 'GuangzhouEvergrande': 577,
 'Jubilo Iwata': 578,
 'Montedio Yamagata': 579,
 'Reutlingen': 580,
 'KFC Uerdingen': 581,
 'Dordrecht': 582,
 'Paysandu SC': 583,
 'Norwich City': 584,
 'Gainare Tottori': 585,
 'Yanbian FC': 586,
 'Estoril': 587,
 'Mansfield Town': 588,
 'Hacken': 589,
 'Northwich': 590,
 'Bury': 591,
 'Fagiano': 592,
 'FK Krasnodar': 593,
 'Malaga B': 594,
 'Curico Unido': 595,
 'Grays': 596,
 'San Francisco Deltas': 597,
 'Samsunspor': 598,
 'MC El Eulma': 599,
 'Clermont': 600,
 'Viking Stavanger': 601,
 'Neuchatel Xamax': 602,
 'Sturm Graz': 603,
 'Malmo FF': 604,
 'Mallorca': 605,
 'Oostende': 606,
 'Maritzburg Classic': 607,
 'Chippa United': 608,
 'Graafschap': 609,
 'Hapoel Acre FC': 610,
 'Arsenal Sarandi': 611,
 'Real Sociedad': 612,
 'Gwangju FC': 613,
 'Gil Vicente': 614,
 'San Lorenzo': 615,
 'Guangzhou Rich and Force': 616,
 'Sivasspor': 617,
 'Puerto Rico FC': 618,
 'Barnet': 619,
 'Iraklis': 620,
 'Zwickau': 621,
 'Jeonbuk FC': 622,
 'Chunnam Dragons': 623,
 'Empoli': 624,
 'Kansas City Wizards': 625,
 'Vestsjalland': 626,
 'Leverkusen': 627,
 'Preston North End': 628,
 'AS Beziers': 629,
 'Greuther Furth': 630,
 'Real Esppor Club': 631,
 'Yokohama Marinos': 632,
 'Horsens': 633,
 'Vila Nova FC GO': 634,
 'Arezzo': 635,
 'Panahaiki': 636,
 'Kalamaria': 637,
 'Oldham Athletic': 638,
 'Beijing Guoan': 639,
 'US Luzenac': 640,
 'FC Basel': 641,
 'Newcastle United Jets': 642,
 'Ionikos': 643,
 'Otago United': 644,
 'Arsenal': 645,
 'Rapide Oued Zem': 646,
 'AC Lala FC': 647,
 'Vallecano': 648,
 'LDU Quito': 649,
 'Antofagasta': 650,
 'Le Mans': 651,
 'Maghrib de Fes': 652,
 'Molde FK': 653,
 'Santa Clara': 654,
 'Union San Felipe': 655,
 'Tours': 656,
 'Egaleo': 657,
 'Indios Juarez': 658,
 'Nantes': 659,
 'JEF United': 660,
 'Shrewsbury Town': 661,
 'Brescia': 662,
 'Dunfermline Athletic': 663,
 'Go Ahead Eagles': 664,
 'Nimes Olympique': 665,
 'FK Radian-Baikal Irkutsk': 666,
 'Boreham Wood': 667,
 'Erciyesspor': 668,
 'FK Angusht Nazran': 669,
 'Hoffenheim': 670,
 'Elgin City': 671,
 'Thanda Royal Zulu': 672,
 'Batna': 673,
 'Daegu FC': 674,
 'Hapoel Tel Aviv': 675,
 'Club Brugge': 676,
 'Brasiliense': 677,
 'Portsmouth': 678,
 'Club Necaxa': 679,
 'Aldershot': 680,
 'Chesterfield': 681,
 'Stafford Rangers': 682,
 'Ajax Amsterdam': 683,
 'CD Chivas': 684,
 'Orleans': 685,
 'RW Ahlen': 686,
 'Ebbsfleet': 687,
 'Kerkyra': 688,
 'AS Marsa': 689,
 'Bnei Sachnin FC': 690,
 'Valencia': 691,
 'ES Hammam Sousse': 692,
 'Wolfsburg': 693,
 'TianjinTeda': 694,
 'Bnei Yehuda Tel Aviv': 695,
 'MSP Batna': 696,
 'Fakel Voronezh': 697,
 'Kickers Offenbach': 698,
 'Hannover 96': 699,
 'Tromso IL': 700,
 'Chelsea': 701,
 'ShandongLuneng': 702,
 'Frosinone': 703,
 'Canvey Island': 704,
 'Xanthi': 705,
 'Roasso Kumamoto': 706,
 'Olympique du Kef': 707,
 'Club Irapuato': 708,
 'Gremio Porto Alegre': 709,
 'Kouvola': 710,
 'Elazigspor': 711,
 'Atlanta Silverbacks': 712,
 'New Zealand Knights': 713,
 'YoungHeart Manawatu': 714,
 'Aviron Bayonnais': 715,
 'Utrecht': 716,
 'Bordeaux': 717,
 'Kaiserslautern': 718,
 'Sporting Gijon': 719,
 'Mordovia Saransk': 720,
 'Mushuc Runa': 721,
 'Fenerbahce': 722,
 'Heusden Zolder': 723,
 'Raith Rovers': 724,
 'Beveren': 725,
 'Monaco': 726,
 'Rimini': 727,
 'Gremio Prudente': 728,
 'Sevilla Atletico': 729,
 'EA Guingamp': 730,
 'Olympique Medea': 731,
 'Syrianska FC': 732,
 'Caroni FC': 733,
 'Hawkes Bay United FC': 734,
 'Uralan Elista': 735,
 'Granada': 736,
 'Belgrano Cordoba': 737,
 'Queens Park': 738,
 'Cape Town City FC': 739,
 'ES Metlaoui': 740,
 'Las Palmas': 741,
 'Sandefjord Fotball': 742,
 'Wuhan Zall FC': 743,
 'Internacional': 744,
 'Messina': 745,
 'Deportivo La Guaira': 746,
 'Arsenal Tula': 747,
 'Athinaikos': 748,
 'Roma': 749,
 'Leeds United': 750,
 'CA Bordj Bou Arreridj': 751,
 'AS Lyon-Duchere': 752,
 'Gap FC': 753,
 'Gateshead': 754,
 'Hartlepool': 755,
 'FF Jaro': 756,
 'Sanfrecce': 757,
 'Ulsan Hyundai': 758,
 'Waregem': 759,
 'Metropolitanos FC': 760,
 'SuperSport United': 761,
 'Higgins': 762,
 'Rosario Central': 763,
 'Derby County': 764,
 'FC Gifu': 765,
 'Libourne': 766,
 'Ravenna': 767,
 'Toronto FC': 768,
 'HavantW': 769,
 'Atalanta': 770,
 'Xerez': 771,
 'Dortmund II': 772,
 'Gefle IF': 773,
 'St Truiden': 774,
 'Braintree Town': 775,
 'Sydney FC': 776,
 'Stockport': 777,
 'Atletico Celaya': 778,
 'Kilmarnock': 779,
 'Tubize': 780,
 'Leyton Orient': 781,
 'Hamilton Wanderers': 782,
 'Esperance Zarzis': 783,
 'Melbourne City FC': 784,
 'Biskra': 785,
 'Mineros de Guayana': 786,
 'Brentford': 787,
 'Randers FC': 788,
 'Chamois Niortais': 789,
 'Chapecoense': 790,
 'FC Rouen': 791,
 'Pistoiese': 792,
 'Piacenza': 793,
 'Columbus Crew': 794,
 'Mamelodi Sundowns': 795,
 'MVD Rossii': 796,
 'Eibar': 797,
 'Jendouba Sport': 798,
 'Bari 1908': 799,
 'Tamworth': 800,
 'Sangju Sangmu': 801,
 'Harrogate': 802,
 'Zulia FC': 803,
 'Auckland Football Kingz': 804,
 'ASO Chlef': 805,
 'New York City FC': 806,
 'RB Salzburg': 807,
 'Wycombe Wanderers': 808,
 'Wiener Neustadt': 809,
 'Independiente': 810,
 'Akhisar Belediyespor': 811,
 'Panionios': 812,
 'Vancouver Whitecaps': 813,
 'Mogi Mirim': 814,
 'Luverdense': 815,
 'Atletico Socopo': 816,
 'FC Aarau': 817,
 'Leones Negros': 818,
 'Torpedo Vladimir': 819,
 'Caen': 820,
 'AS Khroub': 821,
 'Golden Arrows': 822,
 'CA Colon': 823,
 'GyE Jujuy': 824,
 'Esporte Clube Juventude': 825,
 'Icasa': 826,
 'Ranheim': 827,
 'Droylsden': 828,
 'Celta de Vigo': 829,
 'JS Kairouan': 830,
 'Hamilton Academical': 831,
 'St Etienne': 832,
 'Varen Nagasaki': 833,
 'Bradford': 834,
 'CA Bizertin': 835,
 'La Palme Tozeur': 836,
 'Reus Deportiu': 837,
 'Wacker Burghausen': 838,
 'Brommapojkarna': 839,
 'Estrella Roja': 840,
 'Galatasaray': 841,
 'Cercle Brugge': 842,
 'Osmanlispor': 843,
 'Argentinos Juniors': 844,
 'Pacy Vallee': 845,
 'Udinese': 846,
 'Enkopings': 847,
 'Portland Timbers': 848,
 'Sporting Kansas City': 849,
 'Kallithea': 850,
 'Harelbeke': 851,
 'Haka Valkeakoski': 852,
 'RC Kouba': 853,
 'Hallescher FC': 854,
 'Los Angeles FC': 855,
 'Macara': 856,
 'Seattle Sounders': 857,
 'Paradou AC': 858,
 'LDU Portoviejo': 859,
 'Rotor Volgograd': 860,
 'SCR Altach': 861,
 'JSM Bejaia': 862,
 'Livorno': 863,
 'Hameenlinna': 864,
 'Kickers Emden': 865,
 'Helsingborgs IF': 866,
 'Youssoufia Berrechid': 867,
 'Charlton Athletic': 868,
 'AS Cannes': 869,
 'Club Africain': 870,
 'Ironi Ramat HaSharon': 871,
 'Montrose': 872,
 'Benfica': 873,
 'Genclerbirligi': 874,
 'Hapoel Kfar Saba': 875,
 'Miami FC': 876,
 'Alloa Athletic': 877,
 'Colorado Rapids': 878,
 'Goztep': 879,
 'RC Relizane': 880,
 'Erzurumspor': 881,
 'Morecambe': 882,
 'Estrela Amadora': 883,
 'Modena': 884,
 'Munich 1860': 885,
 'Sarpsborg 08': 886,
 'Stromsgodset IF': 887,
 'US Ben Guerdane': 888,
 'Wollongong City Wolves': 889,
 'Cholet': 890,
 'Ehime FC': 891,
 'Medea': 892,
 'Ittihad Khemisset': 893,
 'KAC de Kenitra': 894,
 'New England Revolution': 895,
 'IFK Mariehamn': 896,
 'West Ham United': 897,
 'Guizhou Zhicheng': 898,
 'Barcelona SC': 899,
 'Histon': 900,
 'Watford': 901,
 'Virtus Entella': 902,
 'Parramatta Power': 903,
 'Numancia': 904,
 'NA Hussein Dey': 905,
 'Spezia': 906,
 'Ethnikos Asteras': 907,
 'Bursaspor': 908,
 'Charleroi': 909,
 'Elche': 910,
 'SC Ashdod': 911,
 'Mechelen': 912,
 'Ciudad de Murcia': 913,
 'Leonesa': 914,
 'Kocaelispor': 915,
 'Rochdale': 916,
 'Foggia': 917,

In [17]:
#Dictionary for the difference of winning 

dicWDL={'W':1,'D':0,'L':-1}
dicWDL

{'W': 1, 'D': 0, 'L': -1}

In [18]:
#This is will not be used because it is imply on the "year" column
#Dictionary for the Season (manually)
#dictionarySeason={'00-01':1111,'13-14':1314,'14-15':1415,'15-16':1516,'16-17':1617,'17-18':1718,'18-19':1819,'19-20':1920}
#dictionarySeason
#table['Sea'].unique()

In [19]:
#Dictionary fot the League    #Select only some leagues 
dicitonaryLeagues= {'mar-01':1311901,'ARG1':11871,'AUS1':121191,'AUT1':121201,'BEL1':25121,'BRA1':21811,'BRA2':21812, 'CHE1':308051, 'CHL1':308121, 'CHN1':308141, 'DNK1':414111, 'DZA1':426011, 'ECU1':503211,
 'ENG1':514071, 'ENG2':514072, 'ENG3':514073, 'ENG4':514074, 'ENG5':514075, 'FIN1':609141, 'FRA1':618011, 'FRA2':618012, 'FRA3':618013, 'GER1':705181, 'GER2':705182, 'GER3':705183, 'GRE1':718051, 'HOL1':815121, 'ISR1':919181, 'ITA1':920011, 'ITA2':920012, 'JPN1':1016141, 'JPN2':1016142, 'KOR1':1115181,
 'MEX1':1305241, 'NOR1':1415181, 'NZL1':1426121, 'POR1':1615181, 'RUS1':1821191, 'RUS2':1821192, 'SCO1':1903151, 'SCO2':1903152, 'SCO3':1903153, 'SCO4':1903154, 'SPA1':1916011, 'SPA2':1916012, 'SWE1':1923051, 'TUN1':2021141, 'TUR1':2021181, 'USA1':2119011, 'USA2':2119012, 'VEN1':2205141, 'ZAF1':2601061,
}
dicitonaryLeagues

{'mar-01': 1311901,
 'ARG1': 11871,
 'AUS1': 121191,
 'AUT1': 121201,
 'BEL1': 25121,
 'BRA1': 21811,
 'BRA2': 21812,
 'CHE1': 308051,
 'CHL1': 308121,
 'CHN1': 308141,
 'DNK1': 414111,
 'DZA1': 426011,
 'ECU1': 503211,
 'ENG1': 514071,
 'ENG2': 514072,
 'ENG3': 514073,
 'ENG4': 514074,
 'ENG5': 514075,
 'FIN1': 609141,
 'FRA1': 618011,
 'FRA2': 618012,
 'FRA3': 618013,
 'GER1': 705181,
 'GER2': 705182,
 'GER3': 705183,
 'GRE1': 718051,
 'HOL1': 815121,
 'ISR1': 919181,
 'ITA1': 920011,
 'ITA2': 920012,
 'JPN1': 1016141,
 'JPN2': 1016142,
 'KOR1': 1115181,
 'MEX1': 1305241,
 'NOR1': 1415181,
 'NZL1': 1426121,
 'POR1': 1615181,
 'RUS1': 1821191,
 'RUS2': 1821192,
 'SCO1': 1903151,
 'SCO2': 1903152,
 'SCO3': 1903153,
 'SCO4': 1903154,
 'SPA1': 1916011,
 'SPA2': 1916012,
 'SWE1': 1923051,
 'TUN1': 2021141,
 'TUR1': 2021181,
 'USA1': 2119011,
 'USA2': 2119012,
 'VEN1': 2205141,
 'ZAF1': 2601061}

##### Replacing dictionaries in dataframe

In [21]:
table1['HT']=table1['HT'].replace(dictionary_Teams)

C:\Users\Dell\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [13]:
#table1['Sea']=table1['Sea'].replace(dictionarySeason)

In [22]:
table1['WDL']=table1['WDL'].replace(dicWDL)

C:\Users\Dell\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [23]:
table1['AT']=table1['AT'].replace(dictionary_Teams)

C:\Users\Dell\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [24]:
table1['Lge']=table1['Lge'].replace(dicitonaryLeagues)

C:\Users\Dell\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [25]:
table1

           Sea      Lge       Date    HT    AT  HS  AS  GD  WDL  Year
180185  08-sep  1415181 2008-03-29   493  1032   1   0   1    1  2008
180186  08-sep  1415181 2008-03-30   989    10   2   0   2    1  2008
180187  08-sep  1415181 2008-03-30   288   700   1   1   0    0  2008
180188  08-sep  1415181 2008-03-30   653  1015   0   0   0    0  2008
180189  08-sep  1415181 2008-03-30   601   887   1   0   1    1  2008
...        ...      ...        ...   ...   ...  ..  ..  ..  ...   ...
182750   19-20  1415181 2019-05-25   493   288   0   3  -3   -1  2019
182751   19-20  1415181 2019-05-26  1181  1437   0   1  -1   -1  2019
182752   19-20  1415181 2019-05-26  1076  1441   1   4  -3   -1  2019
182753   19-20  1415181 2019-05-26   827   887   1   0   1    1  2019
182754   19-20  1415181 2019-05-26   700   653   2   1   1    1  2019

[2570 rows x 10 columns]

# MODELING

### Obtaining the features and label

In [166]:
X = table1[['Year','AT','HT','GD']]  #The features
y = table1[['WDL']] #The label 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 2500, random_state = 0)

In [167]:
X_train

        Year    AT    HT  GD
180558  2009  1015     2  -1
181869  2015   886  1032   0
181352  2013   601  1181   2
182209  2016   887   886   1
181389  2013   288  1032   6
...      ...   ...   ...  ..
181218  2012  1213   601   5
181916  2015   742  1076   0
180948  2011  1441  1501   1
181020  2011   653  1501  -1
181838  2015   989   886   0

[70 rows x 4 columns]

## First trial: Neural Network

In [168]:

scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


clfN = MLPClassifier(hidden_layer_sizes = [1000], alpha = 5.0,
                   random_state = 0, solver='lbfgs').fit(X_train_scaled, y_train)

print('Accuracy of NN classifier on training set: {:.2f}'
     .format(clfN.score(X_train_scaled, y_train)))
print('Accuracy of NN classifier on test set: {:.2f}'
     .format(clfN.score(X_test_scaled, y_test)))

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Accuracy of NN classifier on training set: 0.76
Accuracy of NN classifier on test set: 0.66

## Second trial: XgBoost

In [119]:
#Initialize the modeling with XgBoost



#Define the model
xg_c=xgb.XGBClassifier(seed = 82)

#Training the model

xg_c.fit(X_train, y_train)

#Predict with the model
y_pred = xg_c.predict(X_test)


#Determine the score of the model

y_t=y_test.to_numpy()
i=0
correct= 0
for i in range(len(y_pred)):
    
    if y_t[i]== y_pred[i]:
        
        correct= correct +1
        
    else: 
        correct = correct

from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(y_t, y_pred, average='weighted')

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Dell\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

(1.0, 1.0, 1.0, None)

In [120]:

xg_c.score(X_train, y_train)
xg_c.score(X_test, y_test)

1.0

In [121]:
correct

2500

### Third trial: Gradient Boosted Decision trees

In [122]:
from sklearn.ensemble import GradientBoostingClassifier

clf = GradientBoostingClassifier(learning_rate = 0.01, max_depth = 2, random_state = 0)
clf.fit(X_train, y_train)

print('Breast cancer dataset (learning_rate=0.01, max_depth=2)')
print('Accuracy of GBDT classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of GBDT classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:1454: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Breast cancer dataset (learning_rate=0.01, max_depth=2)
Accuracy of GBDT classifier on training set: 1.00
Accuracy of GBDT classifier on test set: 1.00

### Fourth trial: Naive Bayes Classifiers

In [123]:
from sklearn.naive_bayes import GaussianNB



nbclf = GaussianNB().fit(X_train, y_train)
nbclf.score(X_test, y_test)

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.9964

In [124]:
from sklearn.metrics import mean_squared_error, r2_score

In [37]:
y_predict = nbclf.predict(X_test)

In [38]:
len(y_predict)

2500

In [51]:
print("Mean squared error (linear model): {:.2f}".format(mean_squared_error(y_test, y_predict)))

Mean squared error (linear model): 0.01

### Fifth trial: Support Vector Machine

In [50]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVC


scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

clf = SVC(C=10).fit(X_train_scaled, y_train)

print('RBF-kernel SVC (with MinMax scaling) training set accuracy: {:.2f}'
     .format(clf.score(X_train_scaled, y_train)))
print('RBF-kernel SVC (with MinMax scaling) test set accuracy: {:.2f}'
     .format(clf.score(X_test_scaled, y_test)))

RBF-kernel SVC (with MinMax scaling) training set accuracy: 1.00
RBF-kernel SVC (with MinMax scaling) test set accuracy: 0.88

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

# Pruebas:

In [53]:
X_test
y_prediction_1 = xg_c.predict(X_test)

        Year    AT    HT  GD
180857  2011     2  1434  -3
182566  2018   653   288   0
182166  2016  1015   288  -1
182552  2018   886   278   0
181920  2015  1015    66   3
...      ...   ...   ...  ..
182402  2017   700  1441   2
181790  2014   886   601   1
181514  2013     2   493  -1
180745  2010    66   653  -1
182062  2016   653  1015  -1

[2500 rows x 4 columns]

In [61]:
print(dictionary_Teams['FK Haugesund'])
print(dictionary_Teams['Brann Bergen'])

1441
1181

In [153]:

nbclf_y_test= nbclf.predict([[2019,1441,1181,1]]) #Uses de y_train to predict 
#dicWDL[nbclf_X_test[0]]

clfN_y_test= clfN.predict([[2019,1441,1181,1]]) #Uses de y_train to predict 

clf_y_test= clfN.predict([[2019,1441,1181,1]])  #Uses de y_train to predict

In [164]:
X_testa=(2019,1441,1181,0) #El cero lo puse como si fuera un dummy 
nbclf_y_test= nbclf.predict([X_testa]) 
nbclf.score([X_testa], nbclf_y_test)

1.0

In [169]:
X_testa=(2019,1441,1181,0) #El cero lo puse como si fuera un dummy 
clfN_y_test= clfN.predict([X_testa]) 
clfN.score([X_testa], clfN_y_test)

1.0